### ISSUE TITLE
Method not found: 'System.Threading.Tasks.Task Blazored.SessionStorage.ISessionStorageService.SetItemAsync(System.String, System.Object)'

### ISSUE THREAD

**Issue by tripleacoder** [Blazored/SessionStorage#20] opened 2020-05-29 08:53 UTC
In version 1.0.12, I get the exception:

System.MissingMethodException: Method not found: 'System.Threading.Tasks.Task Blazored.SessionStorage.ISessionStorageService.SetItemAsync(System.String, System.Object)'.

when calling

await this.sessionStorage.SetItemAsync(propertyName, value);

Version 1.0.11 is working fine.

**Comment by chrissainty** [comment] 2020-06-01 08:25
Hi @tripleacoder, I've run the sample projects and everything appears to be working as expected. Can you provide a repro of the issue so I can run it and understand where it's going wrong?

**Comment by chrissainty** [comment] 2020-06-04 12:43
As there hasn't been any further info provided. I'm going to close this issue.

**Closed by chrissainty** 2020-06-04 12:43 UTC
Labels: Bug, Needs: More Information

**Comment by chrissainty** [comment] 2020-06-05 06:54
Thanks @tripleacoder. There possibly was a breaking change between the versions we let slip through hence the error you were seeing.

**Comment by JalilSabri** [comment] 2023-09-22 04:19
I use version 4.0.0 and have the same bug when I call LocalStorage methods. I can't trace the code that the container LocalStorage method.
for example, I have this message in the browser console:
Method not found: 'System.Threading.Tasks.ValueTask`1<System.String> Blazored.LocalStorage.ILocalStorageService.KeyAsync(Int32)

**Comment by chrissainty** [comment] 2023-09-22 04:31
@JalilSabri If you can provide a repro for the issue I can look into this.

**Comment by JalilSabri** [comment] 2023-09-22 04:57
thank you for your following-up,
fortunately, I just updated it to version 4.4.0, and the issue is fixed.
